### ISSUE TITLE
La neurona no funciona en la ficha de una iniciativa

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/tipi-uikit#2]

**Comment by pr3ssh** [comment]
Revisarlo en el entorno de DEV

**Comment by dacmail** [comment]
@pr3ssh una pregunta, aquí no faltan ODS para los colores https://github.com/politicalwatch/tipi-frontend/blob/master/src/components/neuron.vue#L41

**Comment by pr3ssh** [comment]
@dacmail Sí, sí que faltan. Es una cuestión que quería plantearte. Ahora mismo los ODS tienen imágenes y colores relacionados. Las imágenes están en la BD (ver [API](https://api.parlamento2030.es/topics/) y los colores están en el código.

¿Qué propones como mejor solución? O lo metemos todo en la BD o lo metemos en un fichero de configuración tanto en [parlamento2030.es](https://github.com/politicalwatch/parlamento2030.es) como en [tipiciudadano.es](https://github.com/politicalwatch/tipiciudadano.es)

**Comment by dacmail** [comment]
Mmmmm, pues en principio da igual que estén en código o en la api, depende más de qué enfoque le queráis dar, si queréis que cada app pueda decidir colores e iconos, entonces lo dejamos en la config y hacemos que la api no envíe nada relacionado con esto (ni imagen ni color), si preferís que estos atributos sean definidos a través de la api y así ser comunes a todas las apps que se hagan usando este origen de datos, entonces mejor enviar tmb el color en la respuesta de la api, no?

En cualquier caso informame del cambio por que esto afecta a neuron y no se si a algún sitio más

**Comment by pr3ssh** [comment]
Afecta creo que a neurona, two-circles y a la ficha de topics y topic.

Creo que vamos a tirar por guardarlo en la APP porque la referencia a ICON está en la App y no en la API y queda raro que la API devuelva un nombre de un fichero que ella no tiene.
Metemos un fichero para parlamento2030.es y tipiciudadano.es con las temáticas y cada icon y color y uno por defecto por si hay algún problema de nombre de temática que no haga match con los que se encuentran en el fichero.

Te encargas de todo eso? Se puede renombrar los ficheros de imágenes para que sea ods1.png en vez del nombre largo como viene ahora y los colores están en https://www.un.org/sustainabledevelopment/es/sustainable-development-goals/

**Comment by dacmail** [comment]
Perfe, yo me encargo de parametrizar los iconos y colores de temáticas en la app.

Para todo esto sigo sumando horas y te mantengo informado, ok?

**Comment by pr3ssh** [comment]
Ok!

**Comment by dacmail** [comment]
El componente TipiNeuron ya recibe como parámetro los estilos de cada topic para ser representados. Cuando me pases todos los subtopics para la config actualizo la app de parlamento2030 y lo aplico allá donde se usen

**Comment by pr3ssh** [comment]
ack

**Comment by pr3ssh** [comment]
@dacmail Veo que no termina de funcionar la neurona. Chequealo [aquí](https://dev.parlamento2030.es/initiatives/b36b8e050e3a507cec8dc880b15b4281fc4538c0).

**Comment by dacmail** [comment]
Pablo, he metido un console.log en tipi-uikit por que no tengo otra forma de hacer pruebas, yo en local, en esa misma iniciativa, lo veo todo bien: https://www.dropbox.com/s/8g0gohme6x9prpv/Captura%20de%20pantalla%202020-01-16%2008.43.15.png?dl=0

Cuando subas los cambios me dices e intento ver más detalles con el debug.

**Comment by pr3ssh** [comment]
Subido!

**Comment by dacmail** [comment]
Pablo, sorry, pero esto puede ser el coñazo total al no poder depurar yo en local. Acabo de subir otra versión con más console.logs por que no doy con la tecla, a ti no se te ocurre por que en local sí funciona y en dev no, verdad? Por que solo pasa con esa iniciativa

**Comment by dacmail** [comment]
Coño, ahora funciona? https://dev.parlamento2030.es/initiatives/b36b8e050e3a507cec8dc880b15b4281fc4538c0
