### ISSUE TITLE
Las imágenes de las temáticas no se muestran

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/tipi-uikit#3]
Parece ser por urls absolutas al cargarlas.

**Comment by pr3ssh** [comment]
Revisarlo en el entorno de DEV

**Comment by dacmail** [comment]
@pr3ssh pero estas imágenes están en el repo? En el directorio img no están

**Comment by pr3ssh** [comment]
No, perdón. Igual te lo dije pero hace tiempo. Los assets específicos de cada proyecto (TIPIC y P2030) están en sus ramas específicas dentro del tipi-frontend.

**Comment by dacmail** [comment]
Ok!! No lo sabía, solucionado en https://github.com/politicalwatch/parlamento2030.es/commit/3a6ed02fff05db2d31f8d72a8635f83f2bdf055b
